### PR TITLE
Restructuring, refactoring, RAIRE and command-line interfaces (first steps) 

### PR DESCRIPTION
**Pull request by dvukcevic**
This PR includes many changes.  In brief:

* Rearrange the files into a standard Python package structure and conventions.  Package can now be easily installed using `pip install`. Installation instructions included in the README.
* Some refactoring to improve maintainability and extensibility.
* Included the RAIRE Python code (not yet fully integrated).
* Included command-line interfaces, one to RAIRE and one to a wrapper script that runs IRV ballot-polling audits.  The latter is somewhat messy but is a working first.
* Harmonised the software licences, to AGPL 3.0

### CODE REVIEW

**Comment by dvukcevic** [comment]
Have fixed conflicts due to the most recent merge (edbfa9b) and fixed an error in the main config file.  Should now be ready for merging.

**Review by pbstark — CHANGES_REQUESTED** [review]
Thank you for the restructuring and development--looks great overall! 

I generally use initial uppercase letters for folders ("Examples/" rather than "examples/") but I understand it's not standard. If we're doing that for "examples/," should also do it for "data/" and other subdirectories. I also strongly prefer that class constants not contain internal spaces, so "FIXED_BET" rather than "FIXED BET," for example.

Unless there's a good argument against it, I think the init for NonnegMean should take callables for `estim`, `test`, and `bet`, not strs--or at least have the option of passing callables. Limiting it to strings makes experimentation harder: can't try new estimators, tests, or betting strategies without rebuilding the library to contain those.

**Comment by fleverest** [comment]
> Unless there's a good argument against it, I think the init for NonnegMean should take callables for `estim`, `test`, and `bet`, not strs--or at least have the option of passing callables. Limiting it to strings makes experimentation harder: can't try new estimators, tests, or betting strategies without rebuilding the library to contain those.

Good point, I reverted these changes. I think, in the future, it would be good to define the different options for estim, test and bet in separate objects. I plan to experiment with different configurations soon.

**Comment by dvukcevic** [comment]
I've fixed the folder names, and a few other small details.

**Review by pbstark — APPROVED** [review]

**Pull request merged**
